#!/bin/bash -l
#SBATCH -J pricer.%j
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=10
#SBATCH --cpus-per-task=1

echo "Multi-threaded execution"

echo "Loading modules..."
module purge
module load toolchain/gompi
module load numlib/OpenBLAS

echo "Compiling program..."

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
mpic++ -std=c++20 -fopenmp -lopenblas src/main.cc src/{mpimanager,opalgorithm,opexecutor,sdesimulator,leastsquaressolver}/*.cc -o out/prog

echo "Executing program..."
time mpiexec -np $SLURM_NTASKS ./out/prog

echo "Done"
