#!/bin/bash -l
#SBATCH --cpus-per-task 10

echo "Multi-threaded execution"

echo "Loading modules..."
module purge
module load toolchain/gompi

echo "Compiling program..."
g++ -fopenmp src/*.cc -o out/prog

echo "Executing program..."
time ./out/prog

echo "Done"
