#!/bin/bash -l
#SBATCH --cpus-per-task 2

echo "Loading modules..."
module purge
module load compiler/GCC

echo "Compiling program..."
g++ src/*.cc -o out/prog

echo "Executing program..."
./out/prog

echo "Done"
